apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homelab-appset
  namespace: openshift-gitops
spec:
  generators:
    - git:
        repoURL: https://github.com/k-stz/homelab.git
        revision: HEAD
        # This looks for all directories directly under gitops/
        directories:
          - path: gitops/*
  template:
    metadata:
      # {{path.basename}} extracts the folder name (e.g., 'homelab' or 'nextcloud')
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/k-stz/homelab.git
        targetRevision: HEAD
        path: '{{path}}'
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        # You can keep a static namespace or use {{path.basename}} if 
        # you want each app in its own namespace
        namespace: homelab-'{{path.basename}}' 
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          enabled: false
        syncOptions:
          - CreateNamespace=true
