kind: Deployment
apiVersion: apps/v1
metadata:
  name: udp-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udp-echo
  template:
    metadata:
      labels:
        app: udp-echo
    spec:
      containers:
        - name: echo
          image: samos123/udp-echo-server
          ports:
            - containerPort: 33333
              protocol: UDP
              name: udp-echo
          imagePullPolicy: IfNotPresent


---

